version: '3'

services:
  web:
    build: .
    expose:
      - 8000
    environment:
      - PORT=8000
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
